version: '3.1'

services:
  db-samlibser:
    container_name: db-samlibser
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file: .env
  api-samlibser:
    container_name: api-samlibser
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn && yarn build && yarn start:prod
    ports:
      - '3000:3000'
    volumes:
      - .:/api-samlibser
    depends_on:
      - db-samlibser
    env_file: .env
