name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run linter
        run: yarn lint
      - name: Run unit tests
        run: yarn test:unit
      - name: Run e2e tests
        run: yarn test:e2e
